Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,28 +20,28 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: recursive
-
-    - name: Compile LaTeX document
-      uses: xu-cheng/latex-action@v3
-      with:
-        root_file: main.tex
-
-    - name: Check for LaTeX errors and warnings
-      run: |
-        if grep -q "^!" main.log; then
-          echo "LaTeX errors found:"
-          grep "^!" main.log
-          exit 1
-        elif grep -q "Warning:" main.log; then
-          echo "LaTeX warnings found:"
-          grep "Warning:" main.log
-          echo "Build completed with warnings."
-        else
-          echo "LaTeX build completed successfully without errors or warnings."
-        fi
-
-    - name: Upload PDF
-      uses: actions/upload-artifact@v4
-      with:
-        name: main.pdf
-        path: main.pdf
+            
+      - name: Compile LaTeX document
+        uses: xu-cheng/latex-action@v3
+        with:
+          root_file: main.tex
+  
+      - name: Check for LaTeX errors and warnings
+        run: |
+          if grep -q "^!" main.log; then
+            echo "LaTeX errors found:"
+            grep "^!" main.log
+            exit 1
+          elif grep -q "Warning:" main.log; then
+            echo "LaTeX warnings found:"
+            grep "Warning:" main.log
+            echo "Build completed with warnings."
+          else
+            echo "LaTeX build completed successfully without errors or warnings."
+          fi
+  
+      - name: Upload PDF
+        uses: actions/upload-artifact@v4
+        with:
+          name: main.pdf
+          path: main.pdf
